# Generated by Django 3.1.5 on 2021-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='contraseña',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
