# Generated by Django 3.1.5 on 2021-01-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_upload_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='contraseña',
            new_name='password',
        ),
    ]
