# Generated by Django 2.2.7 on 2021-01-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20210107_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifySign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='')),
                ('upload_sign', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='web',
        ),
        migrations.AddField(
            model_name='perfil',
            name='llave_privada',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='llave_publica',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
