# Generated by Django 2.2.7 on 2021-01-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_auto_20210116_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='llave_privada',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='llave_publica',
            field=models.CharField(max_length=300),
        ),
    ]
