# Generated by Django 2.2.7 on 2021-01-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_auto_20210116_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='llave_privada',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='llave_publica',
            field=models.FileField(upload_to=''),
        ),
    ]
