# Generated by Django 2.2.7 on 2021-01-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20210116_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='llave_privada',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='llave_publica',
            field=models.BinaryField(),
        ),
    ]
