# Generated by Django 3.1.5 on 2021-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_auto_20210118_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='verifysign',
            name='usuario',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
